%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                Exploration of Experimental Probelm Space                %             
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% This file generates figures that show relationships found from the 
% exploration of experimental simulation data recorded in a file.
% The data read within this file are the variables for later modelling.
% A MATLAB Simulink model experiment was conducted to discover the
% behaviour of a solar module. It was found that varying the irradiance and
% resistance of the single diode cell based solar module. The maximum power
% generated by the module is affected.
close all
%% Read Data from file of recorded data from PVsol and Matlab simulations for house and single diode solar module
num=xlsread('position_data.xlsx');

% each module on the roof and wall contains 8 cells in a 2x4 matrix
% (x,y) is the position of the centre of each possible module possition

module_number = num(:,1);    % every possible module position is assigned a number for identity
roof_x = num(1:32,2);        % every possible position on the roof x coordinate
roof_y = num(1:32,3);        % every possible position on the roof y coordinate
o_fact_roof = num(1:32,5);   % obstruction factor on the roof for relative position
o_fact_wall = num(33:52,5);  % obstruction factor on the wall for relative position
wall_x = num(33:52,2);       % every possible position on the wall x coordinate
wall_y = num(33:52,3);       % every possible position on the wall y coordinate
roof_wall_x = num(:,2);      % centre of module x coord
roof_wall_y = num(:,3);      % centre of module y coord
s_freq = num(:,6);           % shading frequency on relative module
o_fact = num(:,5);
Irr_0 = num(:,8);                               % (test & initals)
Irr = [num(:,8) num(:,26) num(:,27)];           % (All data) average yearly irradience on module after impact of shading frequency
Energy_year_0 = num(:,22);                      % (test & initals)
Energy_year = [num(:,22) num(:,28) num(:,29)];  % (All data) kWh average energy generated by module over year in uk with a 10hr day for module configuration from PVsol simulation
R_opt_0 = num(:,17);                            % (test & initals)
R_opt = [num(:,17) num(:,18) num(:,19)];        % (All data) Ohms the optimium resistance that the solar module should be at for the average MPP power to be met for the year from Matlab simulink model experimental data// R=V/2*I;
MPP_power_module = num(:,12);                   % (Watts) Maximim Power Point power that can be achieved for associated irradiance and resistance from Matlab simulink model experimental data
% reshaping data array to vector
a= R_opt;
x = a(:);
b= Irr;
y=b(:);
c= Energy_year;
z=c(:);
%% Exploring recorded experimental data: 1
% Impact of shading frequncy over the year per module and the Average irradience per module over the year - relative to module position from simulation
figure(1)
scatter(s_freq, Irr_0);
xlabel('Shading Frequency over year on module %');
ylabel('Average Irradience over year on module W/m^2');

%% Exploring recorded experimental data: 2
% position on roof and wall and relative shading frequency
figure(2)
F = scatteredInterpolant(roof_wall_x, roof_wall_y, s_freq);
min_roof_wall_x = min(roof_wall_x);
min_roof_wall_y = min(roof_wall_y);
max_roof_wall_x = max(roof_wall_x);
max_roof_wall_y = max(roof_wall_y);
proj_roof_wall_x = linspace(min_roof_wall_x, max_roof_wall_x, 100);
proj_roof_wall_y = linspace(min_roof_wall_y, max_roof_wall_y, 100);
[PROJ_ROOFWALLX, PROJ_ROOFWALLY] = ndgrid(proj_roof_wall_x, proj_roof_wall_y);
PROJ_SFREQ = F(PROJ_ROOFWALLX, PROJ_ROOFWALLY);
surf(PROJ_ROOFWALLX, PROJ_ROOFWALLY, PROJ_SFREQ, 'edgecolor', 'none');
xlabel('roof and wall x ');
ylabel('roof and wall y');
zlabel('shading frequency');
%% Exploring recorded experimental data: 3
% 3D variable plot of all unconstrained experimentally measured data points
% Average energy generated when at maximum power point
% Irradiance per year per module on x 
% (relative to shading freq. of the module)and relative electrical resistance to get maximum power point energy(mpp)
figure(3)
scatter3(x, y, z,'MarkerFaceColor',[0 .75 .75]);
xlabel('Resistance');       % (tuning resistance to achieve maximum possible power from the solar module)
ylabel('Irradiance');       % impacted by shading freq.
zlabel('Enegy generation')  % yearly for the data point measured from experimental simulation
%% Exploring recorded experimental data: 4
% Looking at the impact and relationship between key variables to understand correlation
figure(4)
a = scatterhist(x,z);
xlabel('Resistance');
ylabel('energy_yearly');
figure(5)
b = scatterhist(x,y);
xlabel('Resistance');
ylabel('irr');
figure(6)
c = scatterhist(y,z);
xlabel('irr');
ylabel('energy_yearly');

%% Exploring recorded experimental data: 5
% Obstruction factor vs position
% Roof:
figure(7)
F = scatteredInterpolant(roof_x, roof_y, o_fact_roof);
min_roof_x = min(roof_x);
min_roof_y = min(roof_y);
max_roof_x = max(roof_x);
max_roof_y = max(roof_y);
proj_roof_x = linspace(min_roof_x, max_roof_x, 100);
proj_roof_y = linspace(min_roof_y, max_roof_y, 100);
[PROJ_ROOFX, PROJ_ROOFY] = ndgrid(proj_roof_x, proj_roof_y);
PROJ_SFREQ = F(PROJ_ROOFX, PROJ_ROOFY);
surf(PROJ_ROOFX, PROJ_ROOFY, PROJ_SFREQ, 'edgecolor', 'none');
xlabel('roof x ');
ylabel('roof y');
zlabel('obstruction factor');
% Wall:
figure(8)
F = scatteredInterpolant(wall_x, wall_y, o_fact_wall);
min_wall_x = min(wall_x);
min_wall_y = min(wall_y);
max_wall_x = max(wall_x);
max_wall_y = max(wall_y);
proj_wall_x = linspace(min_wall_x, max_wall_x, 100);
proj_wall_y = linspace(min_wall_y, max_wall_y, 100);
[PROJ_WALLX, PROJ_WALLY] = ndgrid(proj_wall_x, proj_wall_y);
PROJ_SFREQ = F(PROJ_WALLX, PROJ_WALLY);
surf(PROJ_WALLX, PROJ_WALLY, PROJ_SFREQ, 'edgecolor', 'none');
xlabel('wall x ');
ylabel('wall y');
zlabel('obstruction factor');
